---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: azure-disk-loss-sa
  namespace: default
  labels:
    name: azure-disk-loss-sa
    app.kubernetes.io/part-of: litmus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: azure-disk-loss-sa
  namespace: default
  labels:
    name: azure-disk-loss-sa
    app.kubernetes.io/part-of: litmus
rules:
  - apiGroups: ["", "batch", "litmuschaos.io"]
    resources: ["jobs", "pods", "pods/log", "events", "pods/exec", "chaosengines", "chaosexperiments", "chaosresults", "secrets"]
    verbs: ["create", "list", "get", "patch", "update", "delete"] 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: azure-disk-loss-sa
  namespace: default
  labels:
    name: azure-disk-loss-sa
    app.kubernetes.io/part-of: litmus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: azure-disk-loss-sa
subjects:
- kind: ServiceAccount
  name: azure-disk-loss-sa
  namespace: default